import { and, count, eq } from 'drizzle-orm';
import { DrizzleQueryError } from 'drizzle-orm/errors';
import postgres from 'postgres';

import { db } from '@/db/client';
import { bookings, trialClasses } from '@/db/schema';

import { BookingError } from './errors';
import type { CreateBookingInput } from './schema';

const UNIQUE_VIOLATION = '23505';
const FOREIGN_KEY_VIOLATION = '23503';

// Generated by drizzle from the table and column names. A migration that
// renames either has to be reflected here.
const STUDENT_FK = 'bookings_student_id_students_id_fk';
const TRIAL_CLASS_FK = 'bookings_trial_class_id_trial_classes_id_fk';

// Drizzle wraps driver errors, so the driver error is one level down.
function asPostgresError(error: unknown): postgres.PostgresError | null {
  const cause = error instanceof DrizzleQueryError ? error.cause : error;

  return cause instanceof postgres.PostgresError ? cause : null;
}

// Creating a booking takes no lock and opens no transaction: a pending booking
// holds no seat, so two parents may legitimately hold one for the same last
// seat. The seat race is settled by the payment step, not here.
export async function createBooking(input: CreateBookingInput) {
  const [trialClass] = await db
    .select({ id: trialClasses.id, capacity: trialClasses.capacity })
    .from(trialClasses)
    .where(eq(trialClasses.id, input.trial_class_id));

  if (!trialClass) {
    throw new BookingError('CLASS_NOT_FOUND', 'No trial class with that id.');
  }

  // Only confirmed bookings occupy capacity. Counting pending ones here would
  // reject a parent over a seat nobody has paid for yet. Nothing stops the
  // class filling before the insert, which is why payment checks again.
  const [seats] = await db
    .select({ confirmed: count() })
    .from(bookings)
    .where(
      and(
        eq(bookings.trialClassId, trialClass.id),
        eq(bookings.status, 'confirmed'),
      ),
    );

  if (seats.confirmed >= trialClass.capacity) {
    throw new BookingError('CLASS_FULL', 'This trial class is already full.');
  }

  try {
    const [booking] = await db
      .insert(bookings)
      .values({
        studentId: input.student_id,
        trialClassId: trialClass.id,
        status: 'pending_payment',
      })
      .returning();

    return {
      id: booking.id,
      student_id: booking.studentId,
      trial_class_id: booking.trialClassId,
      status: booking.status,
      confirmed_at: booking.confirmedAt?.toISOString() ?? null,
      created_at: booking.createdAt.toISOString(),
    };
  } catch (error) {
    // The insert is the check. A select before it leaves a window for another
    // request to commit the same live booking, or to delete a row this one just
    // read, so Postgres decides and its error is translated here.
    const pgError = asPostgresError(error);

    if (pgError?.code === UNIQUE_VIOLATION) {
      throw new BookingError(
        'DUPLICATE_BOOKING',
        'This student already has a live booking for this trial class.',
      );
    }

    if (pgError?.code === FOREIGN_KEY_VIOLATION) {
      if (pgError.constraint_name === STUDENT_FK) {
        throw new BookingError('STUDENT_NOT_FOUND', 'No student with that id.');
      }

      if (pgError.constraint_name === TRIAL_CLASS_FK) {
        throw new BookingError('CLASS_NOT_FOUND', 'No trial class with that id.');
      }
    }

    throw error;
  }
}
